### ISSUE TITLE
Roadmap: web-based QMRA tool for AQUANES

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.qmra#5]
### Decisions:

1. The tool should be executed through the AquaNES DSS. This would be just a selection button that executes the link to the tool. Within the tool there should also be a link back to the DSS.
2.  The R based tool of KWB will be used as the back-end calculator. Patrick, Wolfgang and Michael will be  in contact on further changes of settings / improvements *(peer to peer discussion) (summer 2018), 
3. The platform containing data, tools and front end can (in principle) also run other tools. This is not foreseen within aquaNES

### Actions:

**Generic**
* [ ] `Thomas checks available microbial data in different sites (esp. site 8)`
* [ ] ` Thomas will organize a conference call in the week before July 21st, in order to align activities on the data terminology and (additional) parameter requirements between Patrick, Michael, Ulf and Mark – Ulf will fix the agenda`
* [ ] ` Ulf selects Greek site for QMRA`

**Data**
* [ ] `Define uniform naming and units for parameters and system settings and characteristics: Wastewater treatment + AquaNES demonstrated technologies (Michael KWB), Drinking water treatment (Patrick KWR) Deadline july 21st`, **for progress check [#1](https://github.com/KWB-R/kwb.qmra/issues/1)**
* [ ] `Develop initial (default value) dataset in order to enable to run the system (Michael KWB) (July?? 2018)`, **for progress check [#2](https://github.com/KWB-R/kwb.qmra/issues/2)**
* [ ] `Compile database with available data from KWR-KWB, AquaNES other sources for more comprehensive and interactive QMRA and apply uniform structure on naming (KWB, KWR) (filling until the end of project)`, **for progress check [#3](https://github.com/KWB-R/kwb.qmra/issues/3)**

**Back-end / engine**
* [ ] `R-tool potentially adapted after peer to peer discussions and QMRA spot comparison (Wolfgang/Michael KWB, Patrick KWR), (deadline November?)`, **for progress check [#4](https://github.com/KWB-R/kwb.qmra/issues/4)**

**Web based interface / front end**
* [ ] `Feed back from Budapest WW on front end design (storyboard) in conference call or similar (Mark, (Alifta), Anthony (Patrick) ; contacts through Thomas KWR) (deadline july)`
* [ ] `Adapt tool with feedback Budapest WW (Mark, (Alifta), Anthony??) (deadline sept 2018)`
* [ ] `Test dummy run of beta version by Budapest water under supervision of QMRA team (people to be appointed) deadline nov 2018 >> suggestion in long breakout session in Athens m 30 meeting on site instead of via internet, include also other partners from workpackage 1, 2, 3?!`

_Source: email from Thomas (received: 2018-06-08 10:03)_
